### PR TITLE
Remove support for Swift 4.x; Update CI builds

### PR DESCRIPTION
**Pull request by dannys42**
Remove support for Swift 4.x; Update CI builds to use community docker images

### CODE REVIEW

**Review by mbarnach — CHANGES_REQUESTED** [review]
All looks good to me, but we should update the REAME also, as part of this PR.
This is a significant change, and we may state that the previous version (before 2.0) should be used for compatibility with version prior to 5.1.

We also need to not forget to push to Cocoapod after the merge ;-)

**Review by mbarnach — COMMENTED** [review]
👍

**Comment by dannys42** [comment]
@mbarnach thanks for the reminder about cocapods. I put a minor comment on old versions in the README.

**Review by mbarnach — COMMENTED** [review]
Looks good!

**Review by mbarnach — APPROVED** [review]

**Pull request merged**
